In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
#chrono = pd.read_csv('BB_20190227_chronostrat.csv', index_col=('Well','Period'))
#chrono = pd.read_csv('BB_20190227_chronostrat.csv', index_col='Well')
#chrono = pd.read_csv('BB_20190227_chronostrat.csv')
chrono = pd.read_csv('BB_20190227_chrono_csv.csv')
#data = pd.read_csv('BB_20190227_RE_data.csv', index_col='Well')
data = pd.read_csv('BB_20190227_RE_data.csv')

In [17]:
chrono.dropna(inplace=True)

In [10]:
filename = 'BB_20190227_chrono_csv.csv'
with open(filename, 'r') as file:
    chrono = file.read()

In [ ]:
c_dict = {'QUATERNARY': [302.0,1240.0]}

In [18]:
chrono.head()

,Well,Period,Top_depth_m,Base_depth_m,Thickness_m,Top_age_Ma,Bottom_age_Ma
0,6406/2-1,QUATERNARY,302.0,1240.0,938.0,0.00,65.00
1,6406/2-1,UPPER PLIOCENE,1240.0,1690.0,450.0,1.64,2.52
2,6406/2-1,LOWER PLIOCENE,1690.0,1720.0,30.0,3.40,4.30
3,6406/2-1,LOWER PLIOCENE,1720.0,1730.0,10.0,3.40,4.30
4,6406/2-1,UPPER MIOCENE,1730.0,1800.0,70.0,5.20,10.40

In [19]:
data.head()

,Well,Depth m RKB,Formation (NPD),Type of measurement,samplith,tmax,s1,s2,s3,toc,HI,pi,company_name
0,6406/2-1,2510,SPRINGAR FM,DC,SH/CLYST,356.0,2.20,4.61,2.14,1.15,401,0.32,GEOLABNOR
1,6406/2-1,2520,SPRINGAR FM,DC,SH/CLYST,362.0,1.05,3.00,1.74,1.00,300,0.26,GEOLABNOR
2,6406/2-1,2530,SPRINGAR FM,DC,SH/CLYST,360.0,1.85,4.23,2.54,1.01,419,0.30,GEOLABNOR
3,6406/2-1,2540,SPRINGAR FM,DC,CLYST/SH,360.0,1.34,2.97,1.72,0.80,371,0.31,GEOLABNOR(SAGA)
4,6406/2-1,2540,SPRINGAR FM,DC,SH/CLYST,360.0,1.34,2.97,1.72,0.80,371,0.31,GEOLABNOR

In [36]:
data.loc[0]['Depth m RKB']

2510

In [47]:
chrono[data.loc[0]['Well'] == chrono.Well]

,Well,Period,Top_depth_m,Base_depth_m,Thickness_m,Top_age_Ma,Bottom_age_Ma
0,6406/2-1,QUATERNARY,302.0,1240.0,938.0,0.00,65.00
1,6406/2-1,UPPER PLIOCENE,1240.0,1690.0,450.0,1.64,2.52
2,6406/2-1,LOWER PLIOCENE,1690.0,1720.0,30.0,3.40,4.30
3,6406/2-1,LOWER PLIOCENE,1720.0,1730.0,10.0,3.40,4.30
4,6406/2-1,UPPER MIOCENE,1730.0,1800.0,70.0,5.20,10.40
5,6406/2-1,MIDDLE MIOCENE,1800.0,1990.0,190.0,10.40,16.30
6,6406/2-1,LOWER MIOCENE,1990.0,2010.0,20.0,16.30,23.30
7,6406/2-1,UPPER OLIGOCENE,2010.0,2080.0,70.0,23.30,35.40
8,6406/2-1,LOWER OLIGOCENE,2080.0,2192.0,112.0,29.30,35.40
9,6406/2-1,MIDDLE EOCENE,2192.0,2350.0,158.0,38.60,57.20
10,6406/2-1,LOWER EOCENE,2350.0,2386.0,36.0,50.00,57.20
11,6406/2-1,BASAL EOCENE,2386.0,2450.0,64.0,57.00,57.20
12,6406/2-1,UPPER PLIOCENE,2450.0,2503.0,53.0,1.64,2.52
13,6406/2-1,UPPER CAMPANIAN,2503.0,2610.0,107.0,74.00,78.50
14,6406/2-1,MIDDLE CAMPANIAN,2610.0,2690.0,80.0,77.00,80.00
15,6406/2-1,LOWER CAMPANIAN,2690.0,2848.0,158.0,78.50,86.60
16,6406/2-1,SANTONIAN,2848.0,3070.0,222.0,83.00,86.60
17,6406/2-1,CONIACIAN,3070.0,3380.0,310.0,86.60,88.50
18,6406/2-1,UPPER TURONIAN,3380.0,3450.0,70.0,88.50,89.80
19,6406/2-1,LOWER TURONIAN,3450.0,3960.0,510.0,89.80,92.60
20,6406/2-1,UPPER CENOMANIAN,3960.0,4005.0,45.0,90.40,92.60
21,6406/2-1,MIDDLE CENOMANIAN,4005.0,4008.0,3.0,92.60,94.80
22,6406/2-1,LOWER CENOMANIAN,4008.0,4132.0,124.0,94.80,102.00
23,6406/2-1,UPPER ALBIAN,4132.0,4300.0,168.0,97.00,102.00
24,6406/2-1,MIDDLE ALBIAN,4300.0,4340.0,40.0,102.00,112.00
25,6406/2-1,APTIAN,4340.0,4352.0,12.0,112.00,124.50
26,6406/2-1,HAUTERIVIAN,4352.0,4371.0,19.0,131.80,166.10
27,6406/2-1,RYAZANIAN,4371.0,4381.0,10.0,140.70,147.60
28,6406/2-1,OXFORDIAN,4381.0,4389.0,8.0,154.70,157.10
29,6406/2-1,LOWER CALLOVIAN,4389.0,4401.0,12.0,159.90,166.10
30,6406/2-1,MIDDLE BATHONIAN,4401.0,4419.0,18.0,162.90,166.10
31,6406/2-1,LOWER BATHONIAN,4419.0,4575.0,156.0,164.50,173.50
32,6406/2-1,LOWER BAJOCIAN,4575.0,4608.0,33.0,169.80,178.00
33,6406/2-1,AALENIAN,4608.0,4910.0,302.0,173.50,181.00
34,6406/2-1,TOARCIAN,4910.0,4925.0,15.0,178.00,190.40
35,6406/2-1,JURASSIC,4925.0,4931.0,6.0,145.60,208.00
36,6406/2-1,UPPER PLIENSBACHIAN,4931.0,4980.0,49.0,187.00,190.40
37,6406/2-1,LOWER PLIENSBACHIAN,4980.0,5190.0,210.0,190.40,203.50
38,6406/2-1,HETTANGIAN,5190.0,5295.0,105.0,203.50,208.00

In [65]:

for i in range(len(data.index)):
    print(data.loc[i]['Depth m RKB'])
    print(chrono[(data.loc[i]['Depth m RKB'] > chrono.Top_depth_m) & (data.loc[i]['Depth m RKB'] < chrono.Base_depth_m)][['Well','Period','Top_depth_m','Base_depth_m']])

2510
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
51  6406/2-2  UPPER PALEOCENE       2480.0        2540.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2520
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
51  6406/2-2  UPPER PALEOCENE       2480.0        2540.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2530
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
51  6406/2-2  UPPER PALEOCENE       2480.0        2540.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2540
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2540
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2550
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2565
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2575
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2590
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2600
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2615
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1   LOWER CAMPANIAN       2440.0        2620.0
2625
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2640
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2650
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2665
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2675
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2690
        Well            Period  Top_depth_m  Base_depth_m
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2700
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2715
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2725
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2740
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2750
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2765
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2775
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2790
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2800
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2815
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2825
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2840
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2850
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2865
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2875
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2890
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2900
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2915
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2925
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2940
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2950
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2965
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2975
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2990
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3000
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3015
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3025
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3040
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3050
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3065
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3075
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3090
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3100
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3115
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3125
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3140
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3150
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3160
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3175
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3190
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3200
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3215
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3225
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3240
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3250
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3265
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3275
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3290
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3300
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3315
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3325
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0

91  6406/3-1     ALBIAN       3205.0        3648.0
3340
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3350
        Well           Period  Top_depth_m  Base_depth_m
17  6406/2-1        CONIACIAN       3070.0        3380.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3365
        Well           Period  Top_depth_m  Base_depth_m
17  6406/2-1        CONIACIAN       3070.0        3380.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3375
        Well           Period  Top_depth_m  Base_depth_m
17  6406/2-1        CONIACIAN       3070.0        3380.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3390
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3400
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3415
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3417
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3420
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3450
        Well           Period  Top_depth_m  Base_depth_m
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3465
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3475
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3490
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3500
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3508
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3514
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3550
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3590
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3660
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
92  6406/3-1       BARREMIAN       3648.0        3662.0
3665
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
93  6406/3-1     PORTLANDIAN       3662.0        3668.0
3680
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
94  6406/3-1       OXFORDIAN       3668.0        3686.0
3690
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
95  6406/3-1  LOWER OXFORDIAN       3686.0        3698.0
3700
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3708
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3710
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3720
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3721
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3740
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3760
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3780
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3800
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3820
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3840
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3860
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3880
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3900
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
98  6406/3-1        AALENIAN       3895.0        4031.0
3920
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
98  6406/3-1        AALENIAN       3895.0        4031.0
3940
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
98  6406/3-1        AALENIAN       3895.0        4031.0
3960
        Well      Period  Top_depth_m  Base_depth_m
58  6406/2-2  CENOMANIAN       3600.0        4040.0
98  6406/3-1    AALENIAN       3895.0        4031.0
3980
        Well            Period  Top_depth_m  Base_depth_m
20  6406/2-1  UPPER CENOMANIAN       3960.0        4005.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4000
        Well            Period  Top_depth_m  Base_depth_m
20  6406/2-1  UPPER CENOMANIAN       3960.0        4005.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4003
        Well            Period  Top_depth_m  Base_depth_m
20  6406/2-1  UPPER CENOMANIAN       3960.0        4005.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4008
        Well      Period  Top_depth_m  Base_depth_m
58  6406/2-2  CENOMANIAN       3600.0        4040.0
98  6406/3-1    AALENIAN       3895.0        4031.0
4020
        Well            Period  Top_depth_m  Base_depth_m
22  6406/2-1  LOWER CENOMANIAN       4008.0        4132.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4040
        Well            Period  Top_depth_m  Base_depth_m
22  6406/2-1  LOWER CENOMANIAN       4008.0        4132.0
99  6406/3-1    UPPER TOARCIAN       4031.0        4075.0
4060
        Well             Period  Top_depth_m  Base_depth_m
22  6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59  6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
99  6406/3-1     UPPER TOARCIAN       4031.0        4075.0
4080
         Well             Period  Top_depth_m  Base_depth_m
22   6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4100
         Well             Period  Top_depth_m  Base_depth_m
22   6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4120
         Well             Period  Top_depth_m  Base_depth_m
22   6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4132
         Well             Period  Top_depth_m  Base_depth_m
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4140
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4145
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4150
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4160
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4180
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4200
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
101  6406/3-1      PLIENSBACHIAN       4195.0        4255.0
4220
         Well         Period  Top_depth_m  Base_depth_m
23   6406/2-1   UPPER ALBIAN       4132.0        4300.0
60   6406/2-2   UPPER ALBIAN       4215.0        4260.0
101  6406/3-1  PLIENSBACHIAN       4195.0        4255.0
4240
         Well         Period  Top_depth_m  Base_depth_m
23   6406/2-1   UPPER ALBIAN       4132.0        4300.0
60   6406/2-2   UPPER ALBIAN       4215.0        4260.0
101  6406/3-1  PLIENSBACHIAN       4195.0        4255.0
4260
         Well            Period  Top_depth_m  Base_depth_m
23   6406/2-1      UPPER ALBIAN       4132.0        4300.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4280
         Well            Period  Top_depth_m  Base_depth_m
23   6406/2-1      UPPER ALBIAN       4132.0        4300.0
61   6406/2-2      UPPER ALBIAN       4260.0        4285.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4300
         Well            Period  Top_depth_m  Base_depth_m
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4320
         Well            Period  Top_depth_m  Base_depth_m
24   6406/2-1     MIDDLE ALBIAN       4300.0        4340.0
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4330
         Well            Period  Top_depth_m  Base_depth_m
24   6406/2-1     MIDDLE ALBIAN       4300.0        4340.0
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4340
         Well            Period  Top_depth_m  Base_depth_m
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4350
         Well            Period  Top_depth_m  Base_depth_m
25   6406/2-1            APTIAN       4340.0        4352.0
63   6406/2-2      LOWER APTIAN       4345.0        4354.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4352
         Well            Period  Top_depth_m  Base_depth_m
63   6406/2-2      LOWER APTIAN       4345.0        4354.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4355
         Well             Period  Top_depth_m  Base_depth_m
26   6406/2-1        HAUTERIVIAN       4352.0        4371.0
64   6406/2-2  UPPER HAUTERIVIAN       4354.0        4375.0
102  6406/3-1   LOWER SINEMURIAN       4255.0        4705.0
4360
         Well             Period  Top_depth_m  Base_depth_m
26   6406/2-1        HAUTERIVIAN       4352.0        4371.0
64   6406/2-2  UPPER HAUTERIVIAN       4354.0        4375.0
102  6406/3-1   LOWER SINEMURIAN       4255.0        4705.0
4370
         Well             Period  Top_depth_m  Base_depth_m
26   6406/2-1        HAUTERIVIAN       4352.0        4371.0
64   6406/2-2  UPPER HAUTERIVIAN       4354.0        4375.0
102  6406/3-1   LOWER SINEMURIAN       4255.0        4705.0
2550
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2570
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0

89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2600
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2630
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2660
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2690
        Well            Period  Top_depth_m  Base_depth_m
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2720
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2750
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2780
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2790
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2810
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2840
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2860
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2870
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2900
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2910
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2930
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2960
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2990
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3000
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3020
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3050
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3066
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3080
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3100
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3110
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3140
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3170
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3200
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3230
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3247
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3260
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3290
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3320
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3350
        Well           Period  Top_depth_m  Base_depth_m
17  6406/2-1        CONIACIAN       3070.0        3380.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3380
        Well           Period  Top_depth_m  Base_depth_m
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3397
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3400
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3410
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3440
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3442
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3453
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3462
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3470
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3500
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3514
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3530
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3560
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3590
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3610
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3620
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3650
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
92  6406/3-1       BARREMIAN       3648.0        3662.0
3680
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
94  6406/3-1       OXFORDIAN       3668.0        3686.0
3700
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3710
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3740
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3770
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
96  6406/3-1  LOWER OXFORDIAN       3698.0        3775.0
3800
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3830
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3847
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3860
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3890
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
58  6406/2-2       CENOMANIAN       3600.0        4040.0
97  6406/3-1  LOWER BATHONIAN       3775.0        3895.0
3920
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
98  6406/3-1        AALENIAN       3895.0        4031.0
3950
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
98  6406/3-1        AALENIAN       3895.0        4031.0
3980
        Well            Period  Top_depth_m  Base_depth_m
20  6406/2-1  UPPER CENOMANIAN       3960.0        4005.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4010
        Well            Period  Top_depth_m  Base_depth_m
22  6406/2-1  LOWER CENOMANIAN       4008.0        4132.0
58  6406/2-2        CENOMANIAN       3600.0        4040.0
98  6406/3-1          AALENIAN       3895.0        4031.0
4040
        Well            Period  Top_depth_m  Base_depth_m
22  6406/2-1  LOWER CENOMANIAN       4008.0        4132.0
99  6406/3-1    UPPER TOARCIAN       4031.0        4075.0
4047
        Well             Period  Top_depth_m  Base_depth_m
22  6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59  6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
99  6406/3-1     UPPER TOARCIAN       4031.0        4075.0
4070
        Well             Period  Top_depth_m  Base_depth_m
22  6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59  6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
99  6406/3-1     UPPER TOARCIAN       4031.0        4075.0
4100
         Well             Period  Top_depth_m  Base_depth_m
22   6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4120
         Well             Period  Top_depth_m  Base_depth_m
22   6406/2-1   LOWER CENOMANIAN       4008.0        4132.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4160
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4190
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
100  6406/3-1     LOWER TOARCIAN       4075.0        4195.0
4195
        Well             Period  Top_depth_m  Base_depth_m
23  6406/2-1       UPPER ALBIAN       4132.0        4300.0
59  6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
4210
         Well             Period  Top_depth_m  Base_depth_m
23   6406/2-1       UPPER ALBIAN       4132.0        4300.0
59   6406/2-2  MIDDLE CENOMANIAN       4040.0        4215.0
101  6406/3-1      PLIENSBACHIAN       4195.0        4255.0
4250
         Well         Period  Top_depth_m  Base_depth_m
23   6406/2-1   UPPER ALBIAN       4132.0        4300.0
60   6406/2-2   UPPER ALBIAN       4215.0        4260.0
101  6406/3-1  PLIENSBACHIAN       4195.0        4255.0
4280
         Well            Period  Top_depth_m  Base_depth_m
23   6406/2-1      UPPER ALBIAN       4132.0        4300.0
61   6406/2-2      UPPER ALBIAN       4260.0        4285.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4310
         Well            Period  Top_depth_m  Base_depth_m
24   6406/2-1     MIDDLE ALBIAN       4300.0        4340.0
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4340
         Well            Period  Top_depth_m  Base_depth_m
62   6406/2-2      LOWER ALBIAN       4285.0        4345.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4353
         Well            Period  Top_depth_m  Base_depth_m
26   6406/2-1       HAUTERIVIAN       4352.0        4371.0
63   6406/2-2      LOWER APTIAN       4345.0        4354.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4354
         Well            Period  Top_depth_m  Base_depth_m
26   6406/2-1       HAUTERIVIAN       4352.0        4371.0

102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4354
         Well            Period  Top_depth_m  Base_depth_m
26   6406/2-1       HAUTERIVIAN       4352.0        4371.0
102  6406/3-1  LOWER SINEMURIAN       4255.0        4705.0
4370
         Well             Period  Top_depth_m  Base_depth_m
26   6406/2-1        HAUTERIVIAN       4352.0        4371.0
64   6406/2-2  UPPER HAUTERIVIAN       4354.0        4375.0
102  6406/3-1   LOWER SINEMURIAN       4255.0        4705.0
2420
        Well        Period  Top_depth_m  Base_depth_m
11  6406/2-1  BASAL EOCENE       2386.0        2450.0
50  6406/2-2  BASAL EOCENE       2410.0        2480.0
87  6406/3-1        DANIAN       2410.0        2425.0
2440
        Well        Period  Top_depth_m  Base_depth_m
11  6406/2-1  BASAL EOCENE       2386.0        2450.0
50  6406/2-2  BASAL EOCENE       2410.0        2480.0
2460
        Well           Period  Top_depth_m  Base_depth_m
12  6406/2-1   UPPER PLIOCENE       2450.0        2503.0
50  6406/2-2     BASAL EOCENE       2410.0        2480.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2480
        Well           Period  Top_depth_m  Base_depth_m
12  6406/2-1   UPPER PLIOCENE       2450.0        2503.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2500
        Well           Period  Top_depth_m  Base_depth_m
12  6406/2-1   UPPER PLIOCENE       2450.0        2503.0
51  6406/2-2  UPPER PALEOCENE       2480.0        2540.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2520
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
51  6406/2-2  UPPER PALEOCENE       2480.0        2540.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2540
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2560
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2580
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2600
        Well           Period  Top_depth_m  Base_depth_m
13  6406/2-1  UPPER CAMPANIAN       2503.0        2610.0
52  6406/2-2  UPPER CAMPANIAN       2540.0        2710.0
89  6406/3-1  LOWER CAMPANIAN       2440.0        2620.0
2620
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
2640
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2660
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2680
        Well            Period  Top_depth_m  Base_depth_m
14  6406/2-1  MIDDLE CAMPANIAN       2610.0        2690.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2700
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
52  6406/2-2   UPPER CAMPANIAN       2540.0        2710.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2720
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2740
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2760
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2780
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2800
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2820
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2840
        Well            Period  Top_depth_m  Base_depth_m
15  6406/2-1   LOWER CAMPANIAN       2690.0        2848.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2860
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2880
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2900
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
53  6406/2-2   LOWER CAMPANIAN       2710.0        2910.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2920
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2940
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
54  6406/2-2   LOWER CAMPANIAN       2910.0        2950.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2960
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
2980
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3000
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3020
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3040
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3060
        Well            Period  Top_depth_m  Base_depth_m
16  6406/2-1         SANTONIAN       2848.0        3070.0
55  6406/2-2   LOWER SANTONIAN       2950.0        3070.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3080
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3100
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3120
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3140
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3160
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3180
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3198
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3200
        Well            Period  Top_depth_m  Base_depth_m
17  6406/2-1         CONIACIAN       3070.0        3380.0
56  6406/2-2         CONIACIAN       3070.0        3340.0
90  6406/3-1  UPPER CRETACEOUS       2620.0        3205.0
3220
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3240
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3260
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3280
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3300
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3320
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
56  6406/2-2  CONIACIAN       3070.0        3340.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3340
        Well     Period  Top_depth_m  Base_depth_m
17  6406/2-1  CONIACIAN       3070.0        3380.0
91  6406/3-1     ALBIAN       3205.0        3648.0
3360
        Well           Period  Top_depth_m  Base_depth_m
17  6406/2-1        CONIACIAN       3070.0        3380.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3380
        Well           Period  Top_depth_m  Base_depth_m
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3400
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3420
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3440
        Well           Period  Top_depth_m  Base_depth_m
18  6406/2-1   UPPER TURONIAN       3380.0        3450.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3460
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3480
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3500
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3520
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3530
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3540
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3550
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3555
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3560
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3565
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3570
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3575
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3580
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3585
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3590
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3595
        Well           Period  Top_depth_m  Base_depth_m
19  6406/2-1   LOWER TURONIAN       3450.0        3960.0
57  6406/2-2  MIDDLE TURONIAN       3340.0        3600.0
91  6406/3-1           ALBIAN       3205.0        3648.0
3600
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3605
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3610
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3615
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3620
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3625
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0

91  6406/3-1          ALBIAN       3205.0        3648.0
3630
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3635
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3640
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3645
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
91  6406/3-1          ALBIAN       3205.0        3648.0
3650
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
92  6406/3-1       BARREMIAN       3648.0        3662.0
3655
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
92  6406/3-1       BARREMIAN       3648.0        3662.0
3660
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0
92  6406/3-1       BARREMIAN       3648.0        3662.0
3662
        Well          Period  Top_depth_m  Base_depth_m
19  6406/2-1  LOWER TURONIAN       3450.0        3960.0
58  6406/2-2      CENOMANIAN       3600.0        4040.0

In [55]:
len(data.index)

303